In [1]:
#Importing packages
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
%matplotlib inline

In [8]:
#Load The data set
df=pd.read_csv(r"C:\Users\moham\PycharmProjects\Deep Learning\Customer_churn.csv")

In [9]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [10]:
#Drop the Customer Id because it cannot infer anything or mean anything
df.drop('customerID',axis='columns',inplace=True)

In [12]:
#After Dropping the dataframe is
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [15]:
#See the data type
df.dtypes

gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [16]:
#Describing the dataFrame
df.describe

<bound method NDFrame.describe of       gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0     Female              0     Yes         No       1           No
1       Male              0      No         No      34          Yes
2       Male              0      No         No       2          Yes
3       Male              0      No         No      45           No
4     Female              0      No         No       2          Yes
...      ...            ...     ...        ...     ...          ...
7038    Male              0     Yes        Yes      24          Yes
7039  Female              0     Yes        Yes      72          Yes
7040  Female              0     Yes        Yes      11           No
7041    Male              1     Yes         No       4          Yes
7042    Male              0      No         No      66          Yes

         MultipleLines InternetService OnlineSecurity OnlineBackup  \
0     No phone service             DSL             No          Yes
1                   No             DSL            Yes           No
2                   No             DSL            Yes          Yes
3     No phone service             DSL            Yes           No
4                   No     Fiber optic             No           No
...                ...             ...            ...          ...
7038               Yes             DSL            Yes           No
7039               Yes     Fiber optic             No          Yes
7040  No phone service             DSL            Yes           No
7041               Yes     Fiber optic             No           No
7042                No     Fiber optic            Yes           No

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month
1                 Yes          No          No              No        One year
2                  No          No          No              No  Month-to-month
3                 Yes         Yes          No              No        One year
4                  No          No          No              No  Month-to-month
...               ...         ...         ...             ...             ...
7038              Yes         Yes         Yes             Yes        One year
7039              Yes          No         Yes             Yes        One year
7040               No          No          No              No  Month-to-month
7041               No          No          No              No  Month-to-month
7042              Yes         Yes         Yes             Yes        Two year

     PaperlessBilling              PaymentMethod  MonthlyCharges TotalCharges  \
0                 Yes           Electronic check           29.85        29.85
1                  No               Mailed check           56.95       1889.5
2                 Yes               Mailed check           53.85       108.15
3                  No  Bank transfer (automatic)           42.30      1840.75
4                 Yes           Electronic check           70.70       151.65
...               ...                        ...             ...          ...
7038              Yes               Mailed check           84.80       1990.5
7039              Yes    Credit card (automatic)          103.20       7362.9
7040              Yes           Electronic check           29.60       346.45
7041              Yes               Mailed check           74.40        306.6
7042              Yes  Bank transfer (automatic)          105.65       6844.5

     Churn
0       No
1       No
2      Yes
3       No
4      Yes
...    ...
7038    No
7039    No
7040    No
7041   Yes
7042    No

[7043 rows x 20 columns]>

In [18]:
df['TotalCharges'].dtypes

dtype('O')

In [19]:
df['TotalCharges'].isnull()

0       False
1       False
2       False
3       False
4       False
        ...
7038    False
7039    False
7040    False
7041    False
7042    False
Name: TotalCharges, Length: 7043, dtype: bool

In [20]:
pd.to_numeric(df.TotalCharges,errors='coerce').isnull()

0       False
1       False
2       False
3       False
4       False
        ...
7038    False
7039    False
7040    False
7041    False
7042    False
Name: TotalCharges, Length: 7043, dtype: bool

In [24]:
#Convert Total Charges object type to Numeric type
df[pd.to_numeric(df.TotalCharges,errors='coerce').isnull()]
df1 = df[df.TotalCharges!=' ']
df1.TotalCharges = pd.to_numeric(df1.TotalCharges)

C:\Users\moham\Anaconda3\lib\site-packages\pandas\core\generic.py:5208: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [25]:
df1['TotalCharges'].dtypes

dtype('float64')

In [26]:
#Replace yes and no with 1 and 0

df1.replace('No internet service','No',inplace=True)
df1.replace('No phone service','No',inplace=True)

C:\Users\moham\Anaconda3\lib\site-packages\pandas\core\frame.py:4263: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  method=method,

In [27]:
df1

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7040,Female,0,Yes,Yes,11,No,No,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

In [29]:
yes_no_columns = ['Partner','Dependents','PhoneService','MultipleLines','OnlineSecurity','OnlineBackup',
                  'DeviceProtection','TechSupport','StreamingTV','StreamingMovies','PaperlessBilling','Churn']
for col in yes_no_columns:
    df1[col].replace({'Yes': 1,'No': 0},inplace=True)

C:\Users\moham\Anaconda3\lib\site-packages\pandas\core\generic.py:6786: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)

In [30]:
#Replace Gender male and female value with 1 and 0
df1['gender'].replace({'Female':1,'Male':0},inplace=True)

In [32]:
#One hot encoding for the categorical columns
df2 = pd.get_dummies(data=df1, columns=['InternetService','Contract','PaymentMethod'])
df2.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'PaperlessBilling', 'MonthlyCharges', 'TotalCharges', 'Churn',
       'InternetService_DSL', 'InternetService_Fiber optic',
       'InternetService_No', 'Contract_Month-to-month', 'Contract_One year',
       'Contract_Two year', 'PaymentMethod_Bank transfer (automatic)',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='object')

In [33]:
df2

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,InternetService_DSL,InternetService_Fiber optic,InternetService_No,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,1,0,1,0,1,0,0,0,1,0,...,1,0,0,1,0,0,0,0,1,0
1,0,0,0,0,34,1,0,1,0,1,...,1,0,0,0,1,0,0,0,0,1
2,0,0,0,0,2,1,0,1,1,0,...,1,0,0,1,0,0,0,0,0,1
3,0,0,0,0,45,0,0,1,0,1,...,1,0,0,0,1,0,1,0,0,0
4,1,0,0,0,2,1,0,0,0,0,...,0,1,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,0,1,1,24,1,1,1,0,1,...,1,0,0,0,1,0,0,0,0,1
7039,1,0,1,1,72,1,1,0,1,1,...,0,1,0,0,1,0,0,1,0,0
7040,1,0,1,1,11,0,0,1,0,0,...,1,0,0,1,0,0,0,0,1,0
7041,0,1,1,0,4,1,1,0,0,0,...,0,1,0,1,0,0,0,0,0,1
7042,0,0,0,0,66,1,0,1,0,1,...,0,1,0,0,0,1,1,0,0,0

In [34]:
#After Data Preprocessing the datatype is
df2.dtypes

gender                                       int64
SeniorCitizen                                int64
Partner                                      int64
Dependents                                   int64
tenure                                       int64
PhoneService                                 int64
MultipleLines                                int64
OnlineSecurity                               int64
OnlineBackup                                 int64
DeviceProtection                             int64
TechSupport                                  int64
StreamingTV                                  int64
StreamingMovies                              int64
PaperlessBilling                             int64
MonthlyCharges                             float64
TotalCharges                               float64
Churn                                        int64
InternetService_DSL                          uint8
InternetService_Fiber optic                  uint8
InternetService_No                           uint8
Contract_Month-to-month                      uint8
Contract_One year                            uint8
Contract_Two year                            uint8
PaymentMethod_Bank transfer (automatic)      uint8
PaymentMethod_Credit card (automatic)        uint8
PaymentMethod_Electronic check               uint8
PaymentMethod_Mailed check                   uint8
dtype: object

In [35]:
#Scalling
cols_to_scale = ['tenure','MonthlyCharges','TotalCharges']

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df2[cols_to_scale] = scaler.fit_transform(df2[cols_to_scale])

In [36]:
#Splitting the trainning and testing data. Training data in 80% and Testing is 20%
X = df2.drop('Churn',axis='columns') #Select the all coulumn except Churn as X
y = df2['Churn']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=5)

In [48]:
#Building a Artificial Neural Network Model
import tensorflow as tf
from tensorflow import keras

model = keras.Sequential([
    keras.layers.Dense(26, input_shape=(26,), activation='relu'),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train, y_train, epochs=100)

Train on 5625 samples
Epoch 1/100
5625/5625 [==============================] - 1s 136us/sample - loss: 0.4909 - accuracy: 0.7634
Epoch 2/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.4264 - accuracy: 0.7936
Epoch 3/100
5625/5625 [==============================] - 0s 35us/sample - loss: 0.4184 - accuracy: 0.8007
Epoch 4/100
5625/5625 [==============================] - 0s 35us/sample - loss: 0.4143 - accuracy: 0.8057
Epoch 5/100
5625/5625 [==============================] - 0s 35us/sample - loss: 0.4110 - accuracy: 0.8094
Epoch 6/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.4083 - accuracy: 0.8089
Epoch 7/100
5625/5625 [==============================] - 0s 35us/sample - loss: 0.4069 - accuracy: 0.8128
Epoch 8/100
5625/5625 [==============================] - 0s 39us/sample - loss: 0.4043 - accuracy: 0.8126
Epoch 9/100
5625/5625 [==============================] - 0s 38us/sample - loss: 0.4034 - accuracy: 0.8123
Epoch 10/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.4014 - accuracy: 0.8128
Epoch 11/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.4007 - accuracy: 0.8142
Epoch 12/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3994 - accuracy: 0.8148
Epoch 13/100
5625/5625 [==============================] - 0s 35us/sample - loss: 0.3991 - accuracy: 0.8128
Epoch 14/100
5625/5625 [==============================] - 0s 35us/sample - loss: 0.3966 - accuracy: 0.8164
Epoch 15/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3961 - accuracy: 0.8165
Epoch 16/100
5625/5625 [==============================] - 0s 38us/sample - loss: 0.3948 - accuracy: 0.8135
Epoch 17/100
5625/5625 [==============================] - 0s 35us/sample - loss: 0.3941 - accuracy: 0.8137
Epoch 18/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3934 - accuracy: 0.8156
Epoch 19/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3917 - accuracy: 0.8197
Epoch 20/100
5625/5625 [==============================] - 0s 33us/sample - loss: 0.3915 - accuracy: 0.8194
Epoch 21/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3910 - accuracy: 0.8180
Epoch 22/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3899 - accuracy: 0.8172
Epoch 23/100
5625/5625 [==============================] - 0s 36us/sample - loss: 0.3891 - accuracy: 0.8178
Epoch 24/100
5625/5625 [==============================] - 0s 40us/sample - loss: 0.3884 - accuracy: 0.8178
Epoch 25/100
5625/5625 [==============================] - 0s 35us/sample - loss: 0.3877 - accuracy: 0.8197
Epoch 26/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3869 - accuracy: 0.8190
Epoch 27/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3849 - accuracy: 0.8215
Epoch 28/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3849 - accuracy: 0.8226
Epoch 29/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3852 - accuracy: 0.8197
Epoch 30/100
5625/5625 [==============================] - 0s 38us/sample - loss: 0.3841 - accuracy: 0.8194
Epoch 31/100
5625/5625 [==============================] - 0s 37us/sample - loss: 0.3826 - accuracy: 0.8213
Epoch 32/100
5625/5625 [==============================] - 0s 35us/sample - loss: 0.3828 - accuracy: 0.8217
Epoch 33/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3821 - accuracy: 0.8231
Epoch 34/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3810 - accuracy: 0.8213
Epoch 35/100
5625/5625 [==============================] - 0s 37us/sample - loss: 0.3802 - accuracy: 0.8228
Epoch 36/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3795 - accuracy: 0.8235
Epoch 37/100
5625/5625 [==============================] - 0s 35us/sample - loss: 0.3783 - accuracy: 0.8228
Epoch 38/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3793 - accuracy: 0.8212
Epoch 39/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3780 - accuracy: 0.8226
Epoch 40/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3768 - accuracy: 0.8228
Epoch 41/100
5625/5625 [==============================] - 0s 38us/sample - loss: 0.3765 - accuracy: 0.8238
Epoch 42/100
5625/5625 [==============================] - 0s 35us/sample - loss: 0.3751 - accuracy: 0.8238
Epoch 43/100
5625/5625 [==============================] - 0s 35us/sample - loss: 0.3759 - accuracy: 0.8222
Epoch 44/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3745 - accuracy: 0.8261
Epoch 45/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3748 - accuracy: 0.8252
Epoch 46/100
5625/5625 [==============================] - 0s 37us/sample - loss: 0.3729 - accuracy: 0.8265
Epoch 47/100
5625/5625 [==============================] - 0s 36us/sample - loss: 0.3726 - accuracy: 0.8268
Epoch 48/100
5625/5625 [==============================] - 0s 33us/sample - loss: 0.3723 - accuracy: 0.8254
Epoch 49/100
5625/5625 [==============================] - 0s 35us/sample - loss: 0.3710 - accuracy: 0.8272
Epoch 50/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3708 - accuracy: 0.8270
Epoch 51/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3700 - accuracy: 0.8279
Epoch 52/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3699 - accuracy: 0.8263
Epoch 53/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3687 - accuracy: 0.8299
Epoch 54/100
5625/5625 [==============================] - 0s 32us/sample - loss: 0.3700 - accuracy: 0.8277
Epoch 55/100
5625/5625 [==============================] - 0s 32us/sample - loss: 0.3688 - accuracy: 0.8261
Epoch 56/100
5625/5625 [==============================] - 0s 32us/sample - loss: 0.3664 - accuracy: 0.8284
Epoch 57/100
5625/5625 [==============================] - 0s 33us/sample - loss: 0.3671 - accuracy: 0.8276
Epoch 58/100
5625/5625 [==============================] - 0s 33us/sample - loss: 0.3666 - accuracy: 0.8268
Epoch 59/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3657 - accuracy: 0.8281
Epoch 60/100
5625/5625 [==============================] - 0s 33us/sample - loss: 0.3658 - accuracy: 0.8270
Epoch 61/100
5625/5625 [==============================] - 0s 33us/sample - loss: 0.3649 - accuracy: 0.8270
Epoch 62/100
5625/5625 [==============================] - 0s 37us/sample - loss: 0.3636 - accuracy: 0.8276
Epoch 63/100
5625/5625 [==============================] - 0s 39us/sample - loss: 0.3640 - accuracy: 0.8304
Epoch 64/100
5625/5625 [==============================] - 0s 35us/sample - loss: 0.3628 - accuracy: 0.8297
Epoch 65/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3622 - accuracy: 0.8290
Epoch 66/100
5625/5625 [==============================] - 0s 33us/sample - loss: 0.3626 - accuracy: 0.8290
Epoch 67/100
5625/5625 [==============================] - 0s 33us/sample - loss: 0.3622 - accuracy: 0.8288
Epoch 68/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3620 - accuracy: 0.8308
Epoch 69/100
5625/5625 [==============================] - 0s 33us/sample - loss: 0.3604 - accuracy: 0.8306
Epoch 70/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3606 - accuracy: 0.8309
Epoch 71/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3593 - accuracy: 0.8324
Epoch 72/100
5625/5625 [==============================] - 0s 35us/sample - loss: 0.3577 - accuracy: 0.8277
Epoch 73/100
5625/5625 [==============================] - 0s 33us/sample - loss: 0.3606 - accuracy: 0.8268
Epoch 74/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3586 - accuracy: 0.8299
Epoch 75/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3579 - accuracy: 0.8316
Epoch 76/100
5625/5625 [==============================] - 0s 33us/sample - loss: 0.3574 - accuracy: 0.8308
Epoch 77/100

5625/5625 [==============================] - 0s 33us/sample - loss: 0.3570 - accuracy: 0.8304
Epoch 78/100
5625/5625 [==============================] - 0s 32us/sample - loss: 0.3568 - accuracy: 0.8325
Epoch 79/100
5625/5625 [==============================] - 0s 32us/sample - loss: 0.3569 - accuracy: 0.8288
Epoch 80/100
5625/5625 [==============================] - 0s 32us/sample - loss: 0.3569 - accuracy: 0.8315
Epoch 81/100
5625/5625 [==============================] - 0s 33us/sample - loss: 0.3553 - accuracy: 0.8322
Epoch 82/100
5625/5625 [==============================] - 0s 33us/sample - loss: 0.3557 - accuracy: 0.8309
Epoch 83/100
5625/5625 [==============================] - 0s 33us/sample - loss: 0.3537 - accuracy: 0.8320
Epoch 84/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3548 - accuracy: 0.8292
Epoch 85/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3548 - accuracy: 0.8309
Epoch 86/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3527 - accuracy: 0.8324
Epoch 87/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3530 - accuracy: 0.8324
Epoch 88/100
5625/5625 [==============================] - 0s 33us/sample - loss: 0.3524 - accuracy: 0.8329
Epoch 89/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3532 - accuracy: 0.8325
Epoch 90/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3520 - accuracy: 0.8334
Epoch 91/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3521 - accuracy: 0.8347
Epoch 92/100
5625/5625 [==============================] - 0s 33us/sample - loss: 0.3496 - accuracy: 0.8350
Epoch 93/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3507 - accuracy: 0.8325
Epoch 94/100
5625/5625 [==============================] - 0s 33us/sample - loss: 0.3492 - accuracy: 0.8361
Epoch 95/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3487 - accuracy: 0.8350
Epoch 96/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3488 - accuracy: 0.8311
Epoch 97/100
5625/5625 [==============================] - 0s 33us/sample - loss: 0.3501 - accuracy: 0.8327
Epoch 98/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3491 - accuracy: 0.8331
Epoch 99/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3485 - accuracy: 0.8316
Epoch 100/100
5625/5625 [==============================] - 0s 34us/sample - loss: 0.3488 - accuracy: 0.8348

In [49]:
#Evaluating the Mode
model.evaluate(X_test, y_test)

1407/1407 [==============================] - 0s 96us/sample - loss: 0.4838 - accuracy: 0.7761

[0.4837518097156316, 0.7761194]

In [50]:
#Making Prediction
y_predict = model.predict(X_test)

In [51]:
#Set
y_prediction = []
for element in y_predict:
    if element > 0.5:
        y_predict.append(1)
    else:
        y_predict.append(0)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [52]:
y_predict

array([[0.33326355],
       [0.61441797],
       [0.00158512],
       ...,
       [0.8130412 ],
       [0.5833036 ],
       [0.68340844]], dtype=float32)